parameters:
    #Tipo de comprobantes
    COMPROBANTE_ENTREGA : 1
    COMPROBANTE_REASIGNACION : 2
    COMPROBANTE_DESINCORPORACION : 3
    #Tipo de Activos
    ACTIVO_MOBILIARIO : 1
    ACTIVO_EQUIPO : 2
    #Estatus del activo
    STOCK_ALMACEN : 1
    ASIGNADO : 2
    REASIGNADO : 3
    DESINCORPORADO : 4
    #Limite de paginacion
    LIMITE_PAGINACION : 30
    #Acciones a realizar
    OPERACIONES : 1
    CONSULTAS : 2
    REPORTES : 3
    sssss : 4